### PR TITLE
Create docker-image.yml

### PR DESCRIPTION
**Pull request by EdwardKaravakis**
Create docker-image.yml for panda-bigmon-core

### CODE REVIEW

**Comment by EdwardKaravakis** [comment]
panda-server has it on every new release:
on:
  release:
    types: [published]
I believe there are no releases on panda-bigmon-core and commits are committed directly on the master branch (?)

**Comment by tmaeno** [comment]
It would be good to introduce versioning anyway, but you can manually trigger the action since the yaml has

https://github.com/PanDAWMS/panda-bigmon-core/blob/698e2dfbb973f768557864021be40a7e7b037fb0/.github/workflows/docker-image.yml#L11

BTW, you need to put Dockerfile in this repo like 

https://github.com/PanDAWMS/panda-server/blob/master/Dockerfile

**Comment by EdwardKaravakis** [comment]
> It would be good to introduce versioning anyway, but you can manually trigger the action since the yaml has
> 
> https://github.com/PanDAWMS/panda-bigmon-core/blob/698e2dfbb973f768557864021be40a7e7b037fb0/.github/workflows/docker-image.yml#L11
> 
> BTW, you need to put Dockerfile in this repo like
> 
> https://github.com/PanDAWMS/panda-server/blob/master/Dockerfile

Indeed, I might have to change my Dockerfile as I am using a snapshot of the repo and not the version on the main repo (as mentioned in the Tuesday panda core meeting - but that could also come a bit later I guess..

**Comment by EdwardKaravakis** [comment]
Docker file was added along with the required input.

**Review by tmaeno — APPROVED** [review]

**Pull request merged**
